/*
* REDUX
*/

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_POKEMON_PENDING = 'REQUEST_POKEMON_PENDING';
export const REQUEST_POKEMON_SUCCESS = 'REQUEST_POKEMON_SUCCESS';
export const REQUEST_FIRST_IMAGES_SUCCESS = 'REQUEST_FIRST_IMAGES_SUCCESS';
export const REQUEST_POKEMON_FAILED = 'REQUEST_POKEMON_FAILED';
export const REQUEST_MORE_PEOPLE_PENDING = 'REQUEST_MORE_PEOPLE_PENDING';
export const REQUEST_MORE_PEOPLE_SUCCESS = 'REQUEST_MORE_PEOPLE_SUCCESS';
export const REQUEST_MORE_IMAGES_PENDING = 'REQUEST_MORE_IMAGES_PENDING';
export const REQUEST_MORE_IMAGES_SUCCESS = 'REQUEST_MORE_IMAGES_SUCCESS';
export const REQUEST_MORE_PEOPLE_FAILED = 'REQUEST_MORE_PEOPLE_FAILED';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';

/*
* REACT
*/
export const INITIAL_ROUTE = 'main';
export const IMPRINT_ROUTE = 'imprint';
export const TECHNOLOGYINFO_ROUTE = 'technology';